var game = {
    shgabb: 0,
    clickCooldown: 0,
    sw: 0,
    gs: 0,
    upgradeLevels: {
        moreShgabb: 0,
        critChance: 0,
        critBoost: 0,
        shorterCD: 0,
        goodJoke: 0,
        bomblike: 0,
        swChance: 0,
        moreSw: 0,
        autoShgabb: 0,
        fridge: 0,
        divineShgabb: 0,
        shortCD: 0,
        gsBoost1: 0,
        gsBoost2: 0,
    },
    stats: {
        shgabb: 0,
        clicks: 0,
        playTime: 0,
        sw: 0,
        ads: 0,
        gs: 0,
        pr: 0,
    },
}